version: '3.1'
services:
  app:
    container_name: week-9-task
    image: week-9-task
    build: ./
    ports:
      - "8010"
    depends_on:
      - postgresqldb
  postgresqldb:
      image: postgres
      ports:
        - "5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=blogUsersDB